### PR TITLE
Improved colormapping, density and ranges on scatter and sky plots

### PR DESCRIPTION
**Pull request by philippjfr**
Not yet quite working, sky plot range is not correct in certain cases.

### CODE REVIEW

**Comment by timothydmorton** [comment]
I think the colormaps on the skyplot view skyplot and the sky half of the scattersky should be the same; I see they're currently different.

Also, I think we need either a white background so that the low-density regions (locus of points on LH side of plot clustered near zero) is visible... it currently isn't.

**Comment by timothydmorton** [comment]
And in testing, I see that the detail view skyplot shows up once at full range, and then changes the zoom range... having thought about this more, and considering you've said above that something was still not working about it, let's drop the matching-range idea between the two views (assuming that will be easier than fixing it).

You should probably also merge in the `precompute-dataframes` branch from @dharhas; that's what I'm using for testing on lsst-dev because dask works better there.

**Comment by timothydmorton** [comment]
But I do like the coolwarm colormap for the skyplot, and the skyplot view seems to be working much better-- I like the density choice that ensures the empty sky shows up when we zoom in!  So that part looks like it's converging to exactly what we need, thanks!

**Comment by philippjfr** [comment]
>I think the colormaps on the skyplot view skyplot and the sky half of the scattersky should be the same; I see they're currently different.

I just went to respect the actual parameters set on the skyplot and scattersky functions.

> let's drop the matching-range idea between the two views (assuming that will be easier than fixing it).

Not easier than fixing it no. Just ran out of time on Friday.

**Comment by philippjfr** [comment]
@timothydmorton If we're using `coolwarm` should I make it symmetric around zero?

**Comment by philippjfr** [comment]
Another point, on a white background the data is much harder to see.

**Comment by philippjfr** [comment]
Guess I'm still testing with the small dataset though, so I suspect that won't be the case for the full data.

**Pull request merged**
