### PR TITLE
[WIP] add summary view

### PR DESCRIPTION
**Pull request by kcpevey**
Notes:  

* This is built using holoviews (which makes it a little slower due to the data shuffling required). The code for upgrading to geoviews when it becomes available is already included in comment blocks.
* The functionality to type in tracts and have them highlight on the map is not fully formed yet. I can't use the stream for param.depends because we're rebuilding the stream every time the filter or metric changes. Still working out how to resolve this. 
* keeping the same bounds hasn't been added yet
* there is a place to set a default location for the files we need, they are currently empty strings
* this relies on pyviz/label/dev which is anticipated to resolved by releases during the week of 3/9

### CODE REVIEW

**Comment by timothydmorton** [comment]
regarding "rebuilding the stream every time the filter or metric changes"---is it not possible to just redefine the source of the stream rather than rebuild it?  Did you iterate with @philippjfr on this yet?

**Comment by philippjfr** [comment]
That should definitely be possible.

**Comment by kcpevey** [comment]
@timothydmorton I fixed the streams issue. Now as tracts are selected on the map, a list of the tracts is displayed. In order to go the other direction - typing in tracts and they show up as selected on the map, @philippjfr will be putting in a PR to allow for that functionality.  
  
This is the current state:  
Screen Shot 2020-03-10 at 12 40 12 PM

**Comment by kcpevey** [comment]
superceded by #129

**Pull request closed without merging**
