### PR TITLE
New metadata dataset

### PR DESCRIPTION
**Pull request by timothydmorton**
This reads filter, tract info from new metadata file.  This file is in a slightly different format from before; e.g. has list of all visits in a nested dictionary.  This isn't a functional branch yet because it doesn't incorporate the new format of the visit datasets, but could be a starting point to do such.

### CODE REVIEW

**Comment by timothydmorton** [comment]
I am currently running a new iteration of `prepareQADashboard.py` on the whole test dataset, which will be in `/project/tmorton/tickets/DM-21335/w38` when it completes.  `Dataset.connect()` works now with the new datasets; a full `init_dataset` test will have to wait until the full test dataset is generated.

**Comment by timothydmorton** [comment]
OK, this now "works" with the dashboard, but is still very slow.  I am having it compute the coadd table on first load, and that helps with the biggest bottleneck previously.  The performance of the datashaded figures is still borderline unusable though.

**Comment by dharhas** [comment]
Ok will check it out tomorrow.

**Comment by dharhas** [comment]
Need to comment out 
```
331: self.param.trigger('status_message_queue')
497: self.adhoc_js.object = script
```

**Comment by timothydmorton** [comment]
Still getting the partially loaded dashboard

**Comment by timothydmorton** [comment]
And just to confirm, things seem to be working same as before when I revert back to panel 0.6.4; still haven't gotten it to work on 0.7.

**Pull request merged**
